# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6865ba4f23800f11a8c1449badf11c3b"
name = "Bundles-Dev-App"
handle = "bundles-dev-app"
application_url = "https://nc-shine-studies-jar.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-test-store-dr.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://nc-shine-studies-jar.trycloudflare.com/auth/callback",
  "https://nc-shine-studies-jar.trycloudflare.com/auth/shopify/callback",
  "https://nc-shine-studies-jar.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
